"""initial schema

Revision ID: 8cbef0c7e093
Revises: 
Create Date: 2026-06-18 10:19:38.851849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8cbef0c7e093'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'validating', 'validated', 'failed', name='upload_status'), nullable=True),
    sa.Column('valid_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('phone', 'date_format', 'regex', 'required', 'type_check', name='rule_type_enum'), nullable=True),
    sa.Column('rule_key', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.String(length=255), nullable=True),
    sa.Column('digit_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('row_start', sa.Integer(), nullable=True),
    sa.Column('row_end', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validated_rows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('raw_data', mysql.JSON(), nullable=True),
    sa.Column('cleaned_data', mysql.JSON(), nullable=True),
    sa.Column('validation_status', sa.Enum('valid', 'invalid', 'warning', name='validation_status_enum'), nullable=True),
    sa.Column('validation_errors', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validated_rows')
    op.drop_table('chunks')
    op.drop_table('validation_rules')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
